### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by abrusell** [bioinfo-chru-strasbourg/vcf2circos#22]
Hi
after installing and setting the config filepath in options.json file
running the example it exits with many warnings in the stdout, without any output:
`-._    _.--'"`'--._    _.--'"`'--._    _.--'"`'--._    _   
    '-:`.'|`|"':-.  '-:`.'|`|"':-.  '-:`.'|`|"':-.  '.` : '.   
  '.  '.  | |  | |'.  '.  | |  | |'.  '.  | |  | |'.  '.:   '.  '.
  : '.  '.| |  | |  '.  '.| |  | |  '.  '.| |  | |  '.  '.  : '.  `.
  '   '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.'   `.
         `-..,..-'       `-..,..-'       `-..,..-'       `         `
    
                     __ ___      _                   
                    / _|__ \    (_)                  
         __   _____| |_   ) |___ _ _ __ ___ ___  ___ 
         \ \ / / __|  _| / // __| | '__/ __/ _ \/ __|
          \ V / (__| |  / /| (__| | | | (_| (_) \__ \
           \_/ \___|_| |____\___|_|_|  \___\___/|___/
                                                     
                                                     

Author: Jean-Baptiste Lamouche, Antony Le Bechec, Jin Cui
Version: 1.0.1
Last update: January 11 2023

[INFO] Input file: config/Static/example.vcf (format 'vcf')
[INFO] Output file: /g100_scratch/userexternal/abrusell/example.png (format 'png')
[INFO] Options provided.

Function process_vcf(<vcf2circos.plotcategories.plotconfig.Plotconfig object at 0x7f2d8d34e8f0>,) {} Took 0.9905 seconds
Function merge_options(<vcf2circos.plotcategories.link.Link object at 0x7f2d8d1618a0>,) {} Took 0.1174 seconds
   chr_name       size
0      chr1  249250621
3      chr2  243199373
5      chr4  191154276
9      chr5  180915260
18     chr7  159138663
23     chr9  141213431
29    chr11  135006516
31    chr12  133851895
32    chr13  115169878
33    chr14  107349540
34    chr15  102531392
36    chr17   81195210
44    chr19   59128983
47    chr20   63025520
50    chr22   51304566
91     chrX  155270560
[WARN] 5th column is missing for inter-chromosome custom spacing, using default spacing values
[WARN] warning on category "ring"
[WARN] *** warning in arc calculation
[WARN]     interval_theta_array_list:
[WARN]        [[0.009378861891548856, 0.009381563190459038], [0.01090746872479311, 0.010923585463234756], [0.011348048093725038, 0.011356019546790936], [0.011626370177250184, 0.011626670934738651], [0.014358299444124378, 0.014358567090696684]]
[WARN]     assertionError, printing interval_theta_array:
[WARN]        []
[WARN]     the problem index starts from:
[WARN]        (array([], dtype=int64), array([], dtype=int64))
[WARN]     interval_theta_array shape:
[WARN]        (1032, 2)
[WARN] *** warning in arc calculation
[WARN]     interval_theta_array_list:
[WARN]        [[0.009378861891548856, 0.009381563190459038], [0.01090746872479311, 0.010923585463234756], [0.011348048093725038, 0.011356019546790936], [0.011626370177250184, 0.011626670934738651], [0.014358299444124378, 0.014358567090696684]]
[WARN]     assertionError, printing interval_theta_array:
[WARN]        []
[WARN]     the problem index starts from:
[WARN]        (array([], dtype=int64), array([], dtype=int64))
[WARN]     interval_theta_array shape:
[WARN]        (1032, 2)
[WARN] *** warning in arc calculation
[WARN]     interval_theta_array_list:
[WARN]        [[0.009378861891548856, 0.009381563190459038], [0.01090746872479311, 0.010923585463234756], [0.011348048093725038, 0.011356019546790936], [0.011626370177250184, 0.011626670934738651], [0.014358299444124378, 0.014358567090696684]]
[WARN]     assertionError, printing interval_theta_array:
[WARN]        []
[WARN]     the problem index starts from:
[WARN]        (array([], dtype=int64), array([], dtype=int64))
[WARN]     interval_theta_array shape:
[WARN]        (1032, 2)
[WARN] *** warning in arc calculation
[WARN]     interval_theta_array_list:
[WARN]        [[0.009378861891548856, 0.009381563190459038], [0.01090746872479311, 0.010923585463234756], [0.011348048093725038, 0.011356019546790936], [0.011626370177250184, 0.011626670934738651], [0.014358299444124378, 0.014358567090696684]]
[WARN]     assertionError, printing interval_theta_array:
[WARN]        []
[WARN]     the problem index starts from:
[WARN]        (array([], dtype=int64), array([], dtype=int64))
[WARN]     interval_theta_array shape:
[WARN]        (1032, 2)
...
...
...
Function fig(<fig.Figure object at 0x7f2d8d34e7d0>,) {} Took 9.4124 seconds
('<b>chr1:0-2300000<br>p36.33</b>', '<b>chr1:0-2300000<br>p36.33</b>', '<b>chr1:0-2300000<br>p36.33</b>', '<b>chr1:0-2300000<br>p36.33</b>', '<b>chr1:0-2300000<br>p36.33</b>', '<b>chr1:0-2300000<br>p36.33</b>', '<b>chr1:2300000-5400000<br>p36.32</b>', '<b>chr1:2300000-5400000<br>p36.32</b>', '<b>chr1:2300000-5400000<br>p36.32</b>', '<b>chr1:2300000-5400000<br>p36.32</b>', '<b>chr1:2300000-5400000<br>p36.32</b>', '<b>chr1:2300000-5400000<br>p36.32</b>', '<b>chr1:5400000-7200000<br>p36.31</b>', '<b>chr1:5400000-7200000<br>p36.31</b>', '<b>chr1:5400000-7200000<br>p36.31</b>', '<b>chr1:5400000-7200000<br>p36.31</b>', '<b>chr1:5400000-7200000<br>p36.31</b>', '<b>chr1:5400000-7200000<br>p36.31</b>', '<b>chr1:7200000-9200000<br>p36.23</b>', '<b>chr1:7200000-9200000<br>p36.23</b>', '<b>chr1:7200000-9200000<br>p36.23</b>', '<b>chr1:7200000-9200000<br>p36.23</b>', '<b>chr1:7200000-9200000<br>p36.23</b>', '<b>chr1:7200000-9200000<br>p36.23</b>', '<b>chr1:9200000-12700000<br>p36.22</b>', '<b>chr1:9200000-12700000<br>p36.22</b>', '<b>chr1:9200000-12700000<br>p36.22</b>', '<b>chr1:9200000-12700000<br>p36.22</b>', '<b>chr1:9200000-12700000<br>p36.22</b>', '<b>chr1:9200000-12700000<br>p36.22</b>', '<b>chr1:12700000-16200000<br>p36.21</b>', '<b>chr1:12700000-16200000<br>p36.21</b>', '<b>chr1:12700000-16200000<br>p36.21</b>', '<b>chr1:12700000-16200000<br>p36.21</b>', '<b>chr1:12700000-16200000<br>p36.21</b>', '<b>chr1:12700000-16200000<br>p36.21</b>', '<b>chr1:12700000-16200000<br>p36.21</b>', '<b>chr1:12700000-16200000<br>p36.21</b>', '<b>chr1:16200000-20400000<br>p36.13</b>', '<b>chr1:16200000-20400000<br>p36.13</b>', '<b>chr1:16200000-20400000<br>p36.13</b>', '<b>chr1:16200000-20400000<br>p36.13</b>', '<b>chr1:16200000-20400000<br>p36.13</b>', '<b>chr1:16200000-20400000<br>p36.13</b>', '<b>chr1:20400000-23900000<br>p36.12</b>', '<b>chr1:20400000-23900000<br>p36.12</b>', '<b>chr1:20400000-23900000<br>p36.12</b>', '<b>chr1:20400000-23900000<br>p36.12</b>', '<b>chr1:20400000-23900000<br>p36.12</b>', '<b>chr1:20400000-23900000<br>p36.12</b>', '<b>chr1:20400000-23900000<br>p36.12</b>', '<b>chr1:20400000-23900000<br>p36.12</b>', '<b>chr1:23900000-28000000<br>p36.11</b>', '<b>chr1:23900000-28000000<br>p36.11</b>', '<b>chr1:23900000-28000000<br>p36.11</b>', '<b>chr1:23900000-28000000<br>p36.11</b>', '<b>chr1:23900000-28000000<br>p36.11</b>', '<b>chr1:23900000-28000000<br>p36.11</b>', '<b>chr1:23900000-28000000<br>p36.11</b>', '<b>chr1:23900000-28000000<br>p36.11</b>', '<b>chr1:28000000-30200000<br>p35.3</b>', '<b>chr1:28000000-30200000<br>p35.3</b>', '<b>chr1:28000000-30200000<br>p35.3</b>', '<b>chr1:28000000-30200000<br>p35.3</b>', '<b>chr1:28000000-30200000<br>p35.3</b>', '<b>chr1:28000000-30200000<br>p35.3</b>', '<b>chr1:30200000-32400000<br>p35.2</b>', '<b>chr1:30200000-32400000<br>p35.2</b>', '<b>chr1:30200000-32400000<br>p35.2</b>', '<b>chr1:30200000-32400000<br>p35.2</b>', '<b>chr1:30200000-32400000<br>p35.2</b>', '<b>chr1:30200000-32400000<br>p35.2</b>', '<b>chr1:32400000-34600000<br>p35.1</b>', '<b>chr1:32400000-34600000<br>p35.1</b>', '<b>chr1:32400000-34600000<br>p35.1</b>', '<b>chr1:32400000-34600000<br>p35.1</b>', '<b>chr1:32400000-34600000<br>p35.1</b>', '<b>chr1:32400000-34600000<br>p35.1</b>', '<b>chr1:34600000-40100000<br>p34.3</b>', '<b>chr1:34600000-40100000<br>p34.3</b>', '<b>chr1:34600000-40100000<br>p34.3</b>', 
...
...
...
scatter.Marker({
    'color': [gray, gray, gray, ..., gray, gray, gray],
    'opacity': 0,
    'size': 0,
    'symbol': 0
})`

**Comment by abrusell** [comment]
Sorry, here is the commandline:
`$ python vcf2circos/__main__.py --input config/Static/example.vcf --options config/Static/options.json --output $SCRATCH/example.png`

**Comment by JbaptisteLam** [comment]
Hi @abrusell,
My bad I forgot to uncomment some testing, sorry for that
It's now fixed,
Please tell me if it's work now

Best,

Jean-Baptiste

**Comment by abrusell** [comment]
Thank you,
it's working now.
It still produces a lot of warnings:
`[WARN] 5th column is missing for inter-chromosome custom spacing, using default spacing values
[WARN] warning on category "ring"
[WARN] *** warning in arc calculation
[WARN]     interval_theta_array_list:
[WARN]        [[0.009378861891548856, 0.009381563190459038], [0.01090746872479311, 0.010923585463234756], [0.011348048093725038, 0.011356019546790936], [0.011626370177250184, 0.011626670934738651], [0.014358299444124378, 0.014358567090696684]]
[WARN]     assertionError, printing interval_theta_array:
[WARN]        []
[WARN]     the problem index starts from:
[WARN]        (array([], dtype=int64), array([], dtype=int64))
[WARN]     interval_theta_array shape:
[WARN]        (1032, 2)
[WARN] *** warning in arc calculation
[WARN]     interval_theta_array_list:
[WARN]        [[0.009378861891548856, 0.009381563190459038], [0.01090746872479311, 0.010923585463234756], [0.011348048093725038, 0.011356019546790936], [0.011626370177250184, 0.011626670934738651], [0.014358299444124378, 0.014358567090696684]]
[WARN]     assertionError, printing interval_theta_array:
[WARN]        []
[WARN]     the problem index starts from:
[WARN]        (array([], dtype=int64), array([], dtype=int64))
[WARN]     interval_theta_array shape:
[WARN]        (1032, 2)
`

**Comment by JbaptisteLam** [comment]
Yes it's due to the external risk zone calculations but it's not affect the output, it will be adjust in a new release :)
