### ISSUE TITLE
KeyError: "extend"

### ISSUE THREAD

**Issue by asvarvara** [bioinfo-chru-strasbourg/vcf2circos#36]
Hi, I encounter this issue while running this tool:

[INFO] Input file: /home/vcf2circos/diploidSV.annotated.vcf (format 'vcf')
[INFO] Output file: /home/vcf2circos/illumina.html (format 'html')
[INFO] Options provided.

Traceback (most recent call last):
  File "/usr/local/bin/vcf2circos", line 8, in <module>
    sys.exit(main())
  File "/home/vcf2circos/vcf2circos/__main__.py", line 119, in main
    js = Datafactory(input_file, options).plot_dict()
  File "/home/vcf2circos/vcf2circos/datafactory.py", line 25, in plot_dict
    pc = Plotconfig(
  File "/home/vcf2circos/vcf2circos/plotcategories/plotconfig.py", line 100, in __init__
    self.data = self.process_vcf()
  File "/home/vcf2circos/vcf2circos/utils.py", line 459, in timeit_wrapper
    result = func(*args, **kwargs)
  File "/home/vcf2circos/vcf2circos/plotcategories/plotconfig.py", line 174, in process_vcf
    data["Genes"].append(self.get_genes_var(record))
  File "/home/vcf2circos/vcf2circos/plotcategories/plotconfig.py", line 409, in get_genes_var
    if not self.options["Genes"]["extend"]:
KeyError: 'extend'

Can someone help me solving this?

**Comment by JbaptisteLam** [comment]
Hi,

Thanks for using our tools,
I think you didn't set the "Static" key in the json which is required, it's the absolute paht of your "Static" folder provided in the configuration tarball http://www.lbgi.fr/~lamouche/vcf2circos/
Keep me informed if it's worked,

Best,

Jean-Baptiste

**Comment by asvarvara** [comment]
Hi Jean-Baptiste,

Thanks for your reply, unfortunately I had already changed the path in option.json file and change the assembly type to "hg38" before opening the issue.
Do you have any other idea why it does not work?

Best regards,
Angelo

**Comment by JbaptisteLam** [comment]
Can you send me your options.json file at jean-baptiste.lamouche@chru-strasbourg.fr

**Comment by asvarvara** [comment]
Thanks, I just sent you an email

**Comment by JbaptisteLam** [comment]
There is not the "extend" key in your json file, are you sure you downloaded the last configuration folder ?
You should have "extend": false in "Genes" section but you don't have it in your options.json file,

Please add it but I recommend you to use the last one provided in http://www.lbgi.fr/~lamouche/vcf2circos/config_vcf2circos_21082023.tar.gz 

Best, 

Jean-Baptiste
